apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.secretName }}
spec:
  secretName: {{ .Values.secretName }}
  dnsNames:
  - {{ .Values.host }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.host }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer